### ISSUE TITLE
Home Dashboard

### ISSUE THREAD

**Issue by Philipp3107** [Philipp3107/PLAT_GUI_ENTWURF#1]
Needed is a Home Dashboard for the Application.
Elements will be defined.

**Comment by PhilippWork** [comment]
Das ist nicht mehr aktuell. Auf dem Dashboard werden rechts untereinander User angezeigt und links wird die Ordnerhistorie der letzten Importe gezeigt.

**Comment by PhilippWork** [comment]
rechts unter den usern werden dann Konfigurationen angezeigt die vorhanden und auswählbar sind
